# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
